title: mvtechblog
description: ""
author: Mevlut Bulut
url: ""
baseurl: ""

# Varsayılan hero görseli (post/sayfa kendi 'cover' değerini vermezse bu kullanılır)
default_cover: /assets/images/cover-default.jpg

markdown: kramdown
permalink: /:title/

paginate: 5
paginate_path: "/page/:num/"

plugins:
  - jekyll-paginate
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layout: tag
  permalinks:
    tag: "/tag/:name/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
